apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.admission.xphyr.net
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
spec:
  group: admission.xphyr.net
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
   namespace: sidecar-injector
   name: sidecar-injector-webhook-svc
  version: v1