apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
    - name: sidecar-tcpdump
      image: corfr/tcpdump
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sleep
        - infinity
      securityContext:
        privileged: true
